name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]
        node: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: apcu, mbstring, bcmath, pdo_pgsql, opcache, exif, zip, intl, gd, redis, swoole

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install -q --no-ansi \
          --no-interaction --no-scripts --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Run Lint
        run: composer run lint

      - name: Run ESLint
        run: npm run lint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[CHORE]: fix code style"
          commit_options: '--no-verify'
