name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: 'Bu issue, 60 gündür etkinlik göstermediği için otomatik olarak stale olarak işaretlendi. 7 gün içinde güncellenmezse kapanacaktır.'
          stale-pr-message: 'Bu pull request, 60 gündür etkinlik göstermediği için otomatik olarak stale olarak işaretlendi. 7 gün içinde güncellenmezse kapanacaktır.'
          close-issue-message: 'Bu issue, 60 gün boyunca etkinlik göstermediği için otomatik olarak kapatıldı.'
          close-pr-message: 'Bu pull request, 60 gün boyunca etkinlik göstermediği için otomatik olarak kapatıldı.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned,security'
          exempt-pr-labels: 'pinned,security'
