name: Run Tests


on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.4]
        node: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHP Tests
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan test

      - name: Run JS Tests
        run: npm test
